### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by muuuh** [muuuh/docker-airsonos-pi#1]
status: crashes as described here https://github.com/stephen/airsonos/issues/216

```
docker exec airsonos airsonos
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister> Searching for Sonos devices on network...

/usr/local/lib/node_modules/airsonos/node_modules/bluebird/js/main/promise.js:677
             throw e;
```

**Comment by muuuh** [comment]
Fixed

**Comment by jens-maus** [comment]
Sorry, but how exactly have you fixed that? Here I am still having this type of crashes with a Sonos Playbar + two Play:1 as a surround system.

**Comment by muuuh** [comment]
As you can see on my commit I just changed to another (I think the main author's) git repo. Comparing to the other version from justintime - https://github.com/stephen/airsonos/network - stephen seemed to have updated the dependencies, as you can see on his last ommit https://github.com/stephen/airsonos/commit/50d70ce1213567005b106f74c1a33203ab0bdbd9

**Comment by jens-maus** [comment]
Thanks for the hint. However, I have node tunes 0.3.0 running here and still get this crash. Do you have a playbar + two play:1 devices combined as a surround system? The crash mentioned here seems to be related to that device combination...

**Comment by muuuh** [comment]
No, I don't have this device combination. Perhaps you can search in less specific issue trackers like https://github.com/stephen/airsonos/issues or even https://github.com/stephen/airsonos/issues
